const fs = require('fs');
const path = require('path');
const et = require('elementtree');

module.exports = function (context) {
    const projectRoot = context.opts.projectRoot;

    console.log("-----------------------------------------");
    console.log("AdMob MEDIATION SUITE..");
    console.log("-----------------------------------------");

    /**
     * HELPER: Smart Variable Reader
     */
    function getVar(varName) {
        // 1. Try reading from package.json (Cordova CLI)
        try {
            const packageJsonPath = path.join(projectRoot, 'package.json');
            if (fs.existsSync(packageJsonPath)) {
                const packageData = JSON.parse(fs.readFileSync(packageJsonPath, 'utf-8'));
                if (packageData.cordova &&
                    packageData.cordova.plugins &&
                    packageData.cordova.plugins['admob-mediation-suite'] &&
                    packageData.cordova.plugins['admob-mediation-suite'][varName]) {
                    return packageData.cordova.plugins['admob-mediation-suite'][varName];
                }
            }
        } catch (e) {
            // error package.json
        }

        // 2. Try reading from config.xml (Construct 3 / Manual Config)
        try {
            const configPath = path.join(projectRoot, 'config.xml');
            if (fs.existsSync(configPath)) {
                const configRaw = fs.readFileSync(configPath).toString();
                const configXml = et.parse(configRaw);
                const root = configXml.getroot();

                const prefs = root.findall('preference');
                for (let i = 0; i < prefs.length; i++) {
                    if (prefs[i].get('name') === varName) {
                        return prefs[i].get('value');
                    }
                }

                const plugins = root.findall('plugin');
                for (let j = 0; j < plugins.length; j++) {
                    if (plugins[j].get('name') === 'admob-mediation-suite' || plugins[j].get('id') === 'admob-mediation-suite') {
                        const pluginVars = plugins[j].findall('variable');
                        for (let k = 0; k < pluginVars.length; k++) {
                            if (pluginVars[k].get('name') === varName) {
                                return pluginVars[k].get('value');
                            }
                        }
                    }
                }
            }
        } catch (e) {
            // console.warn("Warning reading config.xml:", e.message); 
        }

        return '';
    }

    // Load Variables
    const enableFB = getVar('ENABLE_FACEBOOK') === 'true';
    const enableAppLovin = getVar('ENABLE_APPLOVIN') === 'true';
    const enableUnity = getVar('ENABLE_UNITY') === 'true';
    const keyAppLovin = getVar('KEY_APPLOVIN');
    const enableIronSource = getVar('ENABLE_IRONSOURCE') === 'true';
    const enableVungle = getVar('ENABLE_VUNGLE') === 'true';

    const verFbAndroid = getVar('VER_ANDROID_FACEBOOK') || '6.16.0.0';
    const verAppLovinAndroid = getVar('VER_ANDROID_APPLOVIN') || '11.11.3.0';
    const verUnityAndroid = getVar('VER_ANDROID_UNITY') || '4.9.2.0';
    const verIronSourceAndroid = getVar('VER_ANDROID_IRONSOURCE') || '8.7.0.0';
    const verVungleAndroid = getVar('VER_ANDROID_VUNGLE') || '7.4.3.0';

    const verFbIos = getVar('VER_IOS_FACEBOOK') || '6.12.0.0';
    const verAppLovinIos = getVar('VER_IOS_APPLOVIN') || '11.11.3.0';
    const verUnityIos = getVar('VER_IOS_UNITY') || '4.9.0.0';
    const verIronSourceIos = getVar('VER_IOS_IRONSOURCE') || '8.7.0.0.0';
    const verVungleIos = getVar('VER_IOS_VUNGLE') || '7.4.4.0';

    // =================================================================
    // ANDROID LOGIC
    // =================================================================
    if (context.opts.platforms.includes('android')) {
        const platformRoot = path.join(projectRoot, 'platforms/android');
        const gradleFile = path.join(platformRoot, 'app/build-extras.gradle');
        const manifestFile = path.join(platformRoot, 'app/src/main/AndroidManifest.xml');

        // A. INJECT GRADLE
        let gradleContent = "// Auto-generated by EMI Mediation Suite. DO NOT EDIT.\n";
        gradleContent += "dependencies {\n";

        if (enableFB) {
            gradleContent += `    implementation 'com.google.ads.mediation:facebook:${verFbAndroid}'\n`;
            console.log(`Android: Injecting Facebook Adapter (${verFbAndroid})`);
        }
        if (enableAppLovin) {
            gradleContent += `    implementation 'com.google.ads.mediation:applovin:${verAppLovinAndroid}'\n`;
            console.log(`Android: Injecting AppLovin Adapter (${verAppLovinAndroid})`);
        }
        if (enableUnity) {
            gradleContent += `    implementation 'com.google.ads.mediation:unity:${verUnityAndroid}'\n`;
            console.log(`Android: Injecting Unity Adapter (${verUnityAndroid})`);
        }
        if (enableIronSource) {
            gradleContent += `    implementation 'com.google.ads.mediation:ironsource:${verIronSourceAndroid}'\n`;
            console.log(`Android: Injecting ironSource Adapter (${verIronSourceAndroid})`);
        }
        if (enableVungle) {
            gradleContent += `    implementation 'com.google.ads.mediation:vungle:${verVungleAndroid}'\n`;
            console.log(`Android: Injecting Liftoff/Vungle Adapter (${verVungleAndroid})`);
        }
        gradleContent += "}\n";

        fs.writeFileSync(gradleFile, gradleContent, 'utf-8');

        // B. INJECT MANIFEST
        if (fs.existsSync(manifestFile)) {
            const manifestRaw = fs.readFileSync(manifestFile).toString();
            const manifestTree = et.parse(manifestRaw);
            const root = manifestTree.getroot();
            const appNode = root.find('application');

            let manifestChanged = false;

            if (enableAppLovin && keyAppLovin && appNode) {
                const existing = appNode.findall(`./meta-data[@android:name='applovin.sdk.key']`);
                existing.forEach(node => appNode.remove(node));

                let meta = new et.Element('meta-data');
                meta.set('android:name', 'applovin.sdk.key');
                meta.set('android:value', keyAppLovin);
                appNode.append(meta);
                manifestChanged = true;
                console.log("Android: AppLovin Key Injected to Manifest");
            }

            if (manifestChanged) {
                fs.writeFileSync(manifestFile, manifestTree.write({ indent: 4 }), 'utf-8');
            }
        }
    }

    // =================================================================
    // iOS LOGIC
    // =================================================================
    if (context.opts.platforms.includes('ios')) {
        const platformRoot = path.join(projectRoot, 'platforms/ios');
        const directories = fs.readdirSync(platformRoot).filter(file => fs.statSync(path.join(platformRoot, file)).isDirectory());
        const projName = directories.find(dir => !dir.endsWith('.xcassets') && !dir.endsWith('.xcodeproj') && dir !== 'cordova' && dir !== 'pods');

        const podfile = path.join(platformRoot, 'Podfile');
        const plistFile = path.join(platformRoot, projName, `${projName}-Info.plist`);

        if (fs.existsSync(podfile)) {
            let podContent = fs.readFileSync(podfile, 'utf-8');
            const startMarker = "# AdMob-MEDIATION-START";
            const endMarker = "# AdMob-MEDIATION-END";

            const regex = new RegExp(`${startMarker}[\\s\\S]*?${endMarker}`, 'g');
            podContent = podContent.replace(regex, '');

            let newPods = `\n${startMarker}\n`;
            if (enableFB) newPods += `pod 'GoogleMobileAdsMediationFacebook', '${verFbIos}'\n`;
            if (enableAppLovin) newPods += `pod 'GoogleMobileAdsMediationAppLovin', '${verAppLovinIos}'\n`;
            if (enableUnity) newPods += `pod 'GoogleMobileAdsMediationUnity', '${verUnityIos}'\n`;
            if (enableIronSource) newPods += `pod 'GoogleMobileAdsMediationIronSource', '${verIronSourceIos}'\n`;
            if (enableVungle) newPods += `pod 'GoogleMobileAdsMediationVungle', '${verVungleIos}'\n`;
            newPods += `${endMarker}\n`;

            podContent += newPods;
            fs.writeFileSync(podfile, podContent, 'utf-8');
            console.log("iOS: Podfile updated.");
        }

        if (fs.existsSync(plistFile)) {
            let plistContent = fs.readFileSync(plistFile, 'utf-8');
            const removeRegex = /<key>AppLovinSdkKey<\/key>\s*<string>.*?<\/string>/g;
            plistContent = plistContent.replace(removeRegex, '');

            if (enableAppLovin && keyAppLovin) {
                const insertion = `
    <key>AppLovinSdkKey</key>
    <string>${keyAppLovin}</string>`;
                const lastDictIndex = plistContent.lastIndexOf('</dict>');
                if (lastDictIndex !== -1) {
                    plistContent = plistContent.substring(0, lastDictIndex) + insertion + plistContent.substring(lastDictIndex);
                    console.log("iOS: AppLovin Key Injected to Info.plist");
                }
            }
            fs.writeFileSync(plistFile, plistContent, 'utf-8');
        }
    }

    return Promise.resolve();
};